### ISSUE TITLE
Special types/marks for color values

### ISSUE THREAD

**Issue by SPGoding** [Yurihaia/mc-nbtdoc#1]
@Yurihaia 

The language server I'm working on right now supports color information for color values in SNBTs:  
![](https://raw.githubusercontent.com/SPGoding/datapack-language-server/master/img/color-information.gif)

However, the format currently doesn't have any special marks for these color tags. Will it be a good idea to add a special type `Color` which is a subset of `Int` (and `ColorArray` which is a subset of `IntArray`?) for these colors?

---

BTW, there are also some other values that can represent a color, like the `Color` property of `minecraft:sheep` entities, though I think `Enum`s, which are the current implementations, are more suitable for them.

**Comment by Yurihaia** [comment]
I would probably say that you should just maintain a list of the paths that actually refer to a color. I want to limit how specific the data gets, and color is quite specific, whereas NBTDoc does *need* the concept of registries, so the `id` type is fine (it is a *bit* stretching it)

**Comment by SPGoding** [comment]
I get it, that makes sense. Thanks for explanning!
