### ISSUE TITLE
Generator code

### ISSUE THREAD

**Issue by extremeheat** [Yurihaia/mc-nbtdoc#28]
Hi, this is a great repository, thanks! Currently I was generating this info from the minecraft wiki's wikitext, however this seems a lot more complete. Is the code to generate this data public? I'm guessing that a lot of this is manual, which is OK -- I'm planning on using some of this data for a project that I'm working on. Some insights into how you compiled this data would be nice. :)

**Comment by Yurihaia** [comment]
Almost 100% of the master branch is written manually. The only generated files are those under the `generated` branch (generated with the rust code inside), and the files under `minecraft/generated/*`, which are created with the mod https://github.com/Yurihaia/mc-nbtdoc-generator
