### ISSUE TITLE
What are Registries and where to find them ?

### ISSUE THREAD

**Issue by NitnerocL** [Yurihaia/mc-nbtdoc#39]
In [README](https://github.com/Yurihaia/mc-nbtdoc#needed-registries) you state that some _registries_ are needed.

> ### Needed Registries
> To have a complete validation, the registries specified in [REGISTRY_LIST.md](REGISTRY_LIST.md) should be included.
> Any registries which cannot be accessed should just be validation as a string conforming to the resource location
> format.

What _are_ these registries (i.e. what kind of files) ? And where can I find them to include them ?

**Comment by SPGoding** [comment]
https://github.com/misode/mcmeta/blob/summary/registries/data.json
